### PR TITLE
MTGA_Draft_Tool_V0316

### PR DESCRIPTION
**Pull request by unrealities**
* Fix broken Windows build

### CODE REVIEW

**Comment by JaggerMin** [comment]
Since the 0316 update, adding data sets do not work due to "download failed: couldn't retrieve card data"
Also "taken cards" do not appear properly either

Anyways, thanks for keeping the overlay alive. You are so awesome

**Comment by unrealities** [comment]
> Since the 0316 update, "add data" does not work due to "download failed: couldn't retrieve card data" Also "taken cards" under "cards" do not appear properly either
> 
> Anyways, thanks for keeping the overlay alive. You are so awesome

I'm not seeing this on my Windows or Mac machines. Do you have some firewall or other permissions that need to be updated?

**Comment by JaggerMin** [comment]
> > Since the 0316 update, "add data" does not work due to "download failed: couldn't retrieve card data" Also "taken cards" under "cards" do not appear properly either
> > Anyways, thanks for keeping the overlay alive. You are so awesome
> 
> I'm not seeing this on my Windows or Mac machines. Do you have some firewall or other permissions that need to be updated?

I reinstalled the tool and "data - add sets" works now! But "cards - taken cards" still doesn't show properly. It used to show the full list of cards I took during the draft, which helped me decide how to build my deck after the draft. It doesn't show them anymore. Instead, now it looks like this 

Desktop Screenshot 2024 05 23 - 11 50 15 28

**Comment by unrealities** [comment]
> > > Since the 0316 update, "add data" does not work due to "download failed: couldn't retrieve card data" Also "taken cards" under "cards" do not appear properly either
> > > Anyways, thanks for keeping the overlay alive. You are so awesome
> > 
> > 
> > I'm not seeing this on my Windows or Mac machines. Do you have some firewall or other permissions that need to be updated?
> 
> I reinstalled the tool and "data - add sets" works now! But "cards - taken cards" still doesn't show properly. It used to show the full list of cards I took during the draft, which helped me decide how to build my deck after the draft. It doesn't show them anymore. Instead, now it looks like this

Thank you so much for the details. I broke that, and FiYir helped fix it in 0317!

**Pull request merged**
